# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74e7159ecabfb3152302c644fbe34325e2275e3c3fccb65857e8a9af0d975bebddf6bbb18357f015d79bf1b839624f6565319caab910a436754b58d1a95e9db8

test:
  secret_key_base: f175f130e35bb5cd23c4915647265ba1ed3494a82cc0965f8ea0e2375daeea9bb019faf170c410725ed0c792c67759f3d33cf07356b4ee647c83b094e67fe134

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
